apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: datatub-coming-soon
  name: datatub-coming-soon-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
